In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("customer.csv")
df

,age,gender,review,education,purchased
0,30,Female,Average,School,No
1,68,Female,Poor,UG,No
2,70,Female,Good,PG,No
3,72,Female,Good,PG,No
4,16,Female,Average,UG,No
5,31,Female,Average,School,Yes
6,18,Male,Good,School,No
7,60,Female,Poor,School,Yes
8,65,Female,Average,UG,No
9,74,Male,Good,UG,Yes


In [3]:
from sklearn.preprocessing import LabelEncoder

In [4]:
le=LabelEncoder()

In [5]:
le.fit_transform(df[["purchased"]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0])

In [6]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [8]:
df["purchased"]=le.fit_transform(df[["purchased"]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [9]:
df

,age,gender,review,education,purchased
0,30,Female,Average,School,0
1,68,Female,Poor,UG,0
2,70,Female,Good,PG,0
3,72,Female,Good,PG,0
4,16,Female,Average,UG,0
5,31,Female,Average,School,1
6,18,Male,Good,School,0
7,60,Female,Poor,School,1
8,65,Female,Average,UG,0
9,74,Male,Good,UG,1


In [10]:
from sklearn.preprocessing import OrdinalEncoder

In [12]:
df["education"].nunique()

3

In [13]:
df["education"].unique()

array(['School', 'UG', 'PG'], dtype=object)

In [14]:
df["review"].nunique()

3

In [15]:
df["review"].unique()

array(['Average', 'Poor', 'Good'], dtype=object)

In [16]:
oe=OrdinalEncoder(categories=[["Poor","Average","Good"],["School","UG","PG"]])

In [17]:
oe.fit_transform(df[["review","education"]])

array([[1., 0.],
       [0., 1.],
       [2., 2.],
       [2., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [1., 2.],
       [0., 2.],
       [2., 0.],
       [1., 2.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [1., 0.],
       [0., 0.],
       [2., 1.],
       [1., 2.],
       [2., 0.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [2., 1.]])

In [18]:
df[["review","education"]]=oe.fit_transform(df[["review","education"]])
df

,age,gender,review,education,purchased
0,30,Female,1.0,0.0,0
1,68,Female,0.0,1.0,0
2,70,Female,2.0,2.0,0
3,72,Female,2.0,2.0,0
4,16,Female,1.0,1.0,0
5,31,Female,1.0,0.0,1
6,18,Male,2.0,0.0,0
7,60,Female,0.0,0.0,1
8,65,Female,1.0,1.0,0
9,74,Male,2.0,1.0,1


In [20]:
from sklearn.preprocessing import OneHotEncoder

In [21]:
ohe=OneHotEncoder(sparse_output=False,drop="first")

In [22]:
ohe.fit_transform(df[["gender"]])

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [23]:
encoded=ohe.fit_transform(df[["gender"]])

In [24]:
encoded_df=pd.DataFrame(encoded,columns=ohe.get_feature_names_out(["gender"]))
encoded_df

,gender_Male
0,0.0
1,0.0
2,0.0
3,0.0
4,0.0
5,0.0
6,1.0
7,0.0
8,0.0
9,1.0


In [25]:
df=pd.concat([encoded_df,df],axis=1)
df

,gender_Male,age,gender,review,education,purchased
0,0.0,30,Female,1.0,0.0,0
1,0.0,68,Female,0.0,1.0,0
2,0.0,70,Female,2.0,2.0,0
3,0.0,72,Female,2.0,2.0,0
4,0.0,16,Female,1.0,1.0,0
5,0.0,31,Female,1.0,0.0,1
6,1.0,18,Male,2.0,0.0,0
7,0.0,60,Female,0.0,0.0,1
8,0.0,65,Female,1.0,1.0,0
9,1.0,74,Male,2.0,1.0,1


In [26]:
df.drop(["gender"],axis=1,inplace=True)
df

,gender_Male,age,review,education,purchased
0,0.0,30,1.0,0.0,0
1,0.0,68,0.0,1.0,0
2,0.0,70,2.0,2.0,0
3,0.0,72,2.0,2.0,0
4,0.0,16,1.0,1.0,0
5,0.0,31,1.0,0.0,1
6,1.0,18,2.0,0.0,0
7,0.0,60,0.0,0.0,1
8,0.0,65,1.0,1.0,0
9,1.0,74,2.0,1.0,1


In [ ]:
df=df[[]]